# Generated by Django 3.1 on 2020-08-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
